name: Build and Deploy

on:
  push:
    branches:
      - main  # Change this to your main branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14  # Change this to your Node.js version

    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm run build  # Modify this as per your project setup

    - name: Deploy to GitHub Pages
      run: |
        echo "Building and deploying your site..."
        # Set the API key as an environment variable
        export API_KEY=$API_KEY
        # Deploy your site to GitHub Pages
        # Example: npm run deploy or your deployment script
      env:
        API_KEY: ${{ secrets.API_KEY }}
